name: prerelease
on:
    pull_request

jobs:
    prerelease:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: test coverage
              run: |
                npm ci
                npm run mock-api-background
                sleep 3 # wait for mock-api-background to eget up and running
                npm test 
            - name: Make prerelease to npm
              uses: epeli/npm-release@v1
              with:
                  type: prerelease
                  token: ${{ secrets.NPM_TOKEN }}