name: prerelease
on: pull_request

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - name: test coverage
        run: |
          npm ci
          npm run mock-api-background
          sleep 10 # wait for mock-api-background to eget up and running
          npm test
      - name: Make prerelease to npm
        uses: epeli/npm-release@v1
        with:
          type: prerelease
          token: ${{ secrets.NPM_TOKEN }}
