name: release
on:
  push:
    branches:
      - master

jobs:
  release:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v4
