name: test
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: test coverage
              run: |
                npm run download-docs
                npm ci
                npm run mock-api-background
                while [ -s nohup.out ] # wait for mock-api to be created
                do
                  sleep 1
                done
                npm test -- --coverage
                bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}